stepsPerResolution = [32] * 8
stepsPerResolution_L = [3] * 8
nLevels = 7
kernel = 3
baseLevel = 0
partialLevel = -1
hiddenChannels = 256
n_res_blocks = 3
# zero_use_logscale = True
actNormScale = 1.0
# zero_logscale_factor = 3.0
# y_condition = False  # not implemented
imShape = [3, 128, 128]
perm = "invconv"
coupling = "affine"
# y_classes = 1
# y_learn_top = False
# y_condition = False
# y_weight = 0.01
conditional = True
LU = True