model = "waveletflow"
stepsPerResolution = [32] * 8
stepsPerResolution_L = [3] * 8
nLevels = 7
kernel = 3
baseLevel = 0
partialLevel = -1
hiddenChannels = 256
n_res_blocks = 3
actNormScale = 1.0
imShape = [3, 128, 128]
perm = "invconv"
coupling = "affine"
y_classes = None
y_learn_top = False
y_condition = False
y_weight = None
conditional = True
LU = True
dataset = 'isic'